FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    krb5-user \
    iputils-ping \
    dnsutils \
    curl \
    ldap-utils \
    bc \
    && rm -rf /var/lib/apt/lists/*


COPY config/krb5.conf /etc/krb5.conf

CMD ["sleep", "infinity"]