FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    slapd \
    ldap-utils \
    krb5-kdc \
    krb5-admin-server \
    krb5-config \
    openssl \
    ca-certificates \
    gnupg \
    gettext-base \
    supervisor \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --break-system-packages prometheus_client
RUN systemctl disable slapd 2>/dev/null || true

COPY config/krb5.conf /etc/krb5.conf
COPY config/kdc.conf /etc/krb5kdc/kdc.conf
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY config/ /etc/idm1-config/
COPY config/ldap.conf /etc/ldap/ldap.conf

COPY scripts/init-ldap.sh /usr/local/bin/init-ldap.sh
COPY scripts/init-kerberos.sh /usr/local/bin/init-kerberos.sh
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
COPY scripts/propagate-kerberos.sh /usr/local/bin/propagate-kerberos.sh
COPY scripts/kerberos_exporter.py /usr/local/bin/kerberos_exporter.py
RUN chmod +x /usr/local/bin/*.sh

EXPOSE 389 636 88 88/udp 749 9331

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]