[supervisord]
nodaemon=true

[program:slapd]
command=/usr/sbin/slapd -h "ldap:/// ldapi:/// ldaps:///" -u openldap -g openldap -d 256
autorestart=true
stdout_logfile=/var/log/supervisor/slapd_out.log
stderr_logfile=/var/log/supervisor/slapd_err.log