[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true

[program:slapd]
command=/usr/sbin/slapd -h "ldap:/// ldapi:/// ldaps:///" -u openldap -g openldap -d 256
autorestart=true
stdout_logfile=/var/log/supervisor/slapd_out.log
stderr_logfile=/var/log/supervisor/slapd_err.log

[program:kpropd]
command=/usr/sbin/kpropd -S -d -s /etc/krb5kdc/idm2-host.keytab
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/kpropd.log
stderr_logfile=/var/log/supervisor/kpropd_err.log

[program:krb5kdc]
command=/usr/sbin/krb5kdc -n
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/krb5kdc_out.log
stderr_logfile=/var/log/supervisor/krb5kdc_err.log