[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:slapd]
command=/usr/sbin/slapd -h "ldap:/// ldapi:/// ldaps:///" -u openldap -g openldap -d 256
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/slapd.log
stderr_logfile=/var/log/supervisor/slapd_err.log

[program:krb5kdc]
command=/usr/sbin/krb5kdc -n
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/krb5kdc.log
stderr_logfile=/var/log/supervisor/krb5kdc_err.log

[program:kadmind]
command=/usr/sbin/kadmind -nofork
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/kadmind.log
stderr_logfile=/var/log/supervisor/kadmind_err.log