vrrp_instance VI_LDAP {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    nopreempt

    authentication {
        auth_type PASS
        auth_pass fis2026
    }

    unicast_src_ip 172.28.0.11
    unicast_peer {
        172.28.0.10
    }

    virtual_ipaddress {
        172.28.0.100/24
    }
}